kind = "native"
module = "github.com/kelvralang/time"
import_name = "time"
namespace = "github"
name = "time"
version = "0.2.0"
license = "GPL-3.0-only"
abi_version = 3
kelvra_runtime = "^0.2.0"
author = "Kelvra contributors"
description = "Official Kelvra foundation package."
repository = "https://github.com/kelvralang/time"
dependencies = []

[native]
build = "cmake"
targets = ["linux-x86_64-gnu", "linux-arm64-gnu", "macos-arm64"]
