name: Package CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: read

concurrency:
  group: package-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minimum-runtime:
    uses: moglang/package-actions/.github/workflows/native-ci.yml@v1
    with:
      package_name: time
      runtime_ref: v0.1.4
      targets: '["linux-x86_64-gnu"]'

  current-runtime:
    uses: moglang/package-actions/.github/workflows/native-ci.yml@v1
    with:
      package_name: time
      runtime_ref: main
      targets: '["linux-x86_64-gnu","linux-arm64-gnu","macos-arm64"]'
